packages:
  - 'apps/*'
  - 'packages/*'
  - 'scripts/*'
  - '!test/*'
  - '!scripts/*'
  - '!pnpm-lock.yaml'
  - '!pnpm-workspace.yaml'
  - '!package.json'
  - '!tsconfig.json'
  - '!tsconfig.base.json'
  - '!tsconfig.eslint.json'
  - '!tsconfig.json'
