name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  actions: read
  id-token: write # needed for npm provenance
env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_VERSION: 23

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm ci --legacy-peer-deps
       
      - uses: nrwl/nx-set-shas@v4
      
      - name: Test & Build
        run: |
          npx nx affected -t lint test build
  

