name: CI & Publish

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  actions: read
  id-token: write # needed for npm provenance
env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_VERSION: 23

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      
      # Clean install and reset Nx cache
      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npx nx reset

      #- run: npx playwright install --with-deps

      - uses: nrwl/nx-set-shas@v4

      # Run checks with better error handling
      - name: Run affected targets
        run: |
          npx nx reset
          npx nx affected --target=lint,test,build --parallel --max-parallel=3
        
      # Optional: Run E2E tests separately
      #- name: Run E2E tests
       # run: |
        #  npx nx affected --target=e2e --parallel=1
        #continue-on-error: true

      # Release process only on main branch
      - name: Version and Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ env.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: |
          # Create versions and tags
          npx nx release version
          
          # Build all affected projects
          npx nx affected --target=build
          
          # Publish the packages
          npx nx release publish