name: "BauDevs CI/CD"

on:
  push:
    branches:
      - 'release/@baudevs/*'
    tags:
      - 'release/@baudevs/*'
  create:
    tags:
      - 'release/@baudevs/*'

permissions:
  contents: write
  actions: read
  id-token: write # needed for npm provenance

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_TOKEN || '' }}
  NPM_ACCESS_TOKEN: ${{ secrets.NPM_TOKEN || '' }}
  GITHUB_TOKEN: ${{ secrets.GH_PAT || '' }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || '' }}
  NX_EXCLUDED_PROJECTS: 'baudevs-dashboard,@baudevs/bauCmsNextExample'
  NODE_VERSION: '23.x'
  PNPM_VERSION: '9.15.1'

jobs:
  analyze-changes:
    if: |
      startsWith(github.ref, 'refs/heads/release/') &&
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, 'chore: version plan')
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.extract-info.outputs.project }}
      version_type: ${{ steps.analyze-version.outputs.version_type }}
      needs_human_review: ${{ steps.analyze-version.outputs.needs_review }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Project Info
        id: extract-info
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          PROJECT_NAME=$(echo $BRANCH_NAME | sed 's/release\/@baudevs\///')
          echo "project=$PROJECT_NAME" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install Release Tools Dependencies
        run: |
          cd tools/release-tools
          pnpm install --no-frozen-lockfile
          cd ../../
          echo "Release tools dependencies installed"
          pwd


      - name: Build Release Tools
        run: pnpm nx build @baudevs/release-tools --verbose

      - name: Analyze Changes
        id: analyze-version
        run: node dist/tools/release-tools/analyze-changes.js
        env:
          OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}

  human-review:
    needs: analyze-changes
    if: needs.analyze-changes.outputs.needs_human_review == 'true'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Wait for Human Review
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GH_PAT }}
          approvers: baudevs-team
          minimum-approvals: 1
          issue-title: "Version Type Review Required for ${{ needs.analyze-changes.outputs.project_name }}"
          issue-body: |
            OpenAI analysis needs human review for version type.
            Please select the appropriate version type:
            - patch (bug fixes)
            - minor (new features)
            - major (breaking changes)

            Project: @baudevs/${{ needs.analyze-changes.outputs.project_name }}

            OpenAI Reasoning:
            ${{ steps.analyze-version.outputs.reasoning }}

  create-version-plan:
    needs: [analyze-changes, human-review]
    if: |
      always() &&
      (needs.analyze-changes.outputs.needs_human_review == 'false' ||
       needs.human-review.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Create Version Plan
        run: |
          VERSION_TYPE="${{ needs.analyze-changes.outputs.version_type }}"
          PROJECT="@baudevs/${{ needs.analyze-changes.outputs.project_name }}"

          pnpm nx release plan $VERSION_TYPE \
            --projects=$PROJECT \
            --only-touched=false

      - name: Commit Version Plan
        run: |
          git config --global user.name "baudevs"
          git config --global user.email "tech@baudevs.com"

          git add .nx/version-plans/
          git commit -m "chore(${{ needs.analyze-changes.outputs.project_name }}): add version plan [skip ci]"
          git push

  release:
    needs: create-version-plan
    uses: ./.github/workflows/release-with-plan.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
      NX_TOKEN: ${{ secrets.NX_TOKEN }}

  merge-to-production:
    needs: release
    if: startsWith(github.ref, 'refs/tags/release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: production
          token: ${{ secrets.GH_PAT }}

      - name: Merge Tag to Production
        run: |
          git config --global user.name "baudevs"
          git config --global user.email "tech@baudevs.com"

          # Get the tag name
          TAG_NAME=${GITHUB_REF#refs/tags/}

          # Merge the tag into production
          git fetch origin tag $TAG_NAME
          git merge $TAG_NAME --ff-only

          # Push to production
          git push origin production
