name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  actions: read
  id-token: write # needed for npm provenance

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_TOKEN || '' }}
  NPM_ACCESS_TOKEN: ${{ secrets.NPM_TOKEN || '' }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || '' }}
  NODE_VERSION: 23

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest' # Specify the Bun version or use 'latest'

      - name: Install Dependencies
        run: |
          bun install

      - name: Set SHAs for Affected Commands
        run: |
          bunx nx set-shas

      - name: Run Linting
        run: |
          bunx nx affected -t lint

      - name: Run Tests
        run: |
          bunx nx affected -t test

      - name: Build Affected Projects
        run: |
          bunx nx affected -t build

      - name: Configure Git credentials
        run: |
          git config --global user.name "baudevs"
          git config --global user.email "tech@baudevs.com"

      - name: Execute Release
        run: |
          bunx nx release
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

      - name: Publish Packages
        run: |
          bunx nx release publish
        env:
          NPM_TOKEN: ${{ env.NPM_ACCESS_TOKEN }}
