name: "Release with Version Plan"

on:
  workflow_call:
    inputs:
      project:
        description: "List of project names"
        required: false
        default: "affected"
        type: string
    secrets:
      NX_TOKEN:
        required: true
      NPM_TOKEN:
        required: true
      GH_PAT:
        required: true
      OPENAI_API_KEY:
        required: true
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true
      # GITHUB_TOKEN removed to avoid collision

permissions:
  contents: write       # Allows pushing commits and tags

env:
  GITHUB_TOKEN: ${{ github.token }}
  NX_EXCLUDED_PROJECTS: 'baudevs-dashboard,@baudevs/bauCmsNextExample'
  NODE_VERSION: 23.3.0
  PNPM_VERSION: 9.15.2

jobs:
  release-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}  # Use the environment variable
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install Dependencies
        run: pnpm install

      - name: Set Git User and Update Branch
        run: |
          git config --global user.name "baudevs_tech"
          git config --global user.email "tech@baudevs.com"
          git fetch origin ${{ github.ref }}
          git rebase origin/${{ github.ref_name }}

      - name: Load NPM OTP from 1Password
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          NPM_OTP: "op://BauDevs/npm/one-time password?attribute=otp"

      - name: Execute Release
        run: |
          echo "Releasing ${{inputs.project}}"
          pnpm nx release -y --verbose
      - name: Publish Package

        run: |
          echo "Publishing ${{inputs.project}}"
          if [ -z "$NPM_OTP" ]; then
            echo "Error: NPM_OTP is empty or not set afte OP Action ran..."
            echo "Getting NPM_OTP from 1Password CLI..."
            export NPM_OTP=$(op item get "npm" --otp --vault "BauDevs")
            if [ -z "$NPM_OTP" ]; then
              echo "Error: NPM_OTP is still empty or not set. Exiting."
              exit 1
            fi
          fi
          if [ -z "$NPM_TOKEN" ]; then
            echo "Error: NPM_TOKEN is empty or not set. Exiting."
            exit 1
          fi
          echo "NPM_OTP: $NPM_OTP"
          echo "Setting NPM_TOKEN in .npmrc"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo "Publishing ${{ inputs.project }}"
          pnpm nx release publish ${{ inputs.project }} --verbose --otp=$NPM_OTP
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NX_TOKEN: ${{ secrets.NX_TOKEN }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}  # Inherit from global env
