name: "Release with Version Plan"

on:
  workflow_call:
    inputs:
      project:
        description: "List of project names"
        required: false
        default: "affected"
        type: string
    secrets:
      NX_TOKEN:
        required: true
      NPM_TOKEN:
        required: true
      OPENAI_API_KEY:
        required: true
      GH_TOKEN:       # Added GH_TOKEN
        required: true

env:
  NX_EXCLUDED_PROJECTS: 'baudevs-dashboard,@baudevs/bauCmsNextExample'
  NODE_VERSION: 23.3.0
  PNPM_VERSION: 9.15.2

jobs:
  release-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}  # Use the passed GH_TOKEN
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install Dependencies
        run: pnpm install

      - name: Set Git User and Update Branch
        run: |
          git config --global user.name "baudevs"
          git config --global user.email "tech@baudevs.com"
          git fetch origin ${{ github.ref }}
          git rebase origin/${{ github.ref_name }}

      - name: Execute Release
        run: pnpm nx release --skip-publish --verbose

      - name: Publish Package
        run: pnpm nx release publish @baudevs/${{ inputs.project }} --verbose
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NX_TOKEN: ${{ secrets.NX_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the passed GITHUB_TOKEN
