name: "BauDevs CI/CD"

on:
  push:
    branches:
      - release/@baudevs/bau-log-hero/v.*.*
      - release/@baudevs/bau-gtm-tracker/v.*.*
    tags:
      - release/@baudevs/bau-log-hero/v*.*.*
      - release/@baudevs/bau-gtm-tracker/v*.*.*

permissions:
  contents: write
  actions: read
  id-token: write # needed for npm provenance

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_TOKEN || '' }}
  NPM_ACCESS_TOKEN: ${{ secrets.NPM_TOKEN || '' }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || '' }}
  NODE_VERSION: '23.x'
  NX_EXCLUDED_PROJECTS: 'baudevs-dashboard,@baudevs/bauCmsNextExample'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        id: setShas

      - run: |
          echo "BASE: ${{ steps.setShas.outputs.base }}"
          echo "HEAD: ${{ steps.setShas.outputs.head }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9.15.1'

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run Linting
        run: pnpm nx affected --target=lint --exclude=${{ env.NX_EXCLUDED_PROJECTS }}

      - name: Build Affected Projects
        run: pnpm nx affected --target=build --exclude=${{ env.NX_EXCLUDED_PROJECTS }}

      - name: Configure Git credentials
        run: |
          git config --global user.name "baudevs"
          git config --global user.email "tech@baudevs.com"

      - name: Execute Release
        run: pnpm nx release
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

      - name: Publish Packages
        run: pnpm nx release publish
        env:
          NPM_TOKEN: ${{ env.NPM_ACCESS_TOKEN }}
